/**
 * =============================================================================
 * CALS (CROSS-APP LINK SYNC) TYPE DEFINITIONS
 * =============================================================================
 * 
 * Part of: Buckets V2 Communication Layer
 * V2 Living Index: #5 CALS (Cross-App Link Sync)
 * Frontend Architecture: CALS System
 * 
 * PURPOSE:
 * Type definitions for CALS - the privacy-first, attribution-powered,
 * DNA-aware link-sharing system that connects users across external
 * messaging apps (iMessage, WhatsApp, Instagram, etc.) without reading
 * their private messages.
 * 
 * CONCEPT:
 * CALS is NOT a traditional messenger. It's a shared-link tracker that:
 * 1. User shares Buckets link via ANY app (iMessage, WhatsApp, etc.)
 * 2. Friend opens link → deep link fires → CALS tracks the open
 * 3. CALS creates a "thread" auto-collecting all shared Buckets links
 * 4. Revenue from opens/conversions attributed back to sharer
 * 5. All without reading external messages (privacy-first)
 * 
 * KEY INNOVATION:
 * Like Spotify's "shared in chat" feature, but with attribution tracking
 * and revenue sharing. Turns every share into potential earnings.
 * 
 * INTEGRATION POINTS:
 * - MediaID DNA: Share recommendations based on DNA matching
 * - Treasury: Attribution revenue from link conversions
 * - Coliseum: Track share funnels and conversion rates
 * - Locker: Brand drops attached to threads (opt-in)
 * - All content: Events, tracks, artists, offers can be shared
 * 
 * COMPONENTS USING THESE TYPES:
 * - SharedWithYouTab.tsx (main CALS feed)
 * - ThreadList.tsx (list of conversations)
 * - ThreadView.tsx (single thread with link cards)
 * - LinkCard.tsx (rich preview of shared content)
 * - ShareSheet.tsx (native share with tracking)
 * - AttributionWidget.tsx (earnings from shares)
 * - CALSSettings.tsx (consent management)
 * 
 * DATABASE TABLES:
 * - cals_threads (conversation threads)
 * - cals_thread_items (links shared in threads)
 * - cals_link_events (link open tracking)
 * - cals_consent (user privacy preferences)
 * - cals_attribution_ledger (in treasury.ts)
 * 
 * =============================================================================
 */

// =============================================================================
// THREAD TYPES
// =============================================================================

/**
 * CALS Thread
 * A conversation thread collecting shared Buckets links
 * 
 * Used in: ThreadList, ThreadView components
 * Database: cals_threads table
 * 
 * Creation: Auto-created when two users exchange Buckets links
 * - Can be 1:1 (two people) or group (multiple)
 * - No messages stored, only link opens are tracked
 */
export interface CALSThread {
  id: string

  // Participants
  member_ids: string[]         // User IDs in thread
  is_group: boolean            // True if >2 members

  // Thread metadata
  thread_name?: string         // Optional custom name
  last_activity_ts: Date       // Last link shared or opened
  unread_count?: Record<string, number>  // Per-member unread count

  // Privacy
  visibility: 'private' | 'friends' | 'public'

  // Statistics
  total_links_shared: number
  total_links_opened: number
  total_attributed_revenue_cents: number

  // Status
  is_active: boolean
  is_archived: boolean

  // Metadata
  created_at: Date
  updated_at: Date
}

/**
 * CALS Thread Item
 * Individual item in a thread (link, note, or system message)
 * 
 * Used in: ThreadView component
 * Database: cals_thread_items table
 */
export interface CALSThreadItem {
  id: string
  thread_id: string

  // Item type
  type: 'link' | 'note' | 'system'

  // For link type
  link_id?: string
  link_data?: CALSLinkData

  // For note type (optional text annotations)
  text?: string

  // Sender
  sender_id: string
  sender_name?: string         // Cached for display

  // Engagement
  view_count: number
  open_count: number           // How many times link was opened
  conversion_count: number     // How many conversions from this link

  // Attribution revenue
  attributed_revenue_cents: number

  // Metadata
  metadata?: Record<string, any>
  created_at: Date
}

// =============================================================================
// LINK TYPES
// =============================================================================

/**
 * CALS Link Data
 * Rich preview data for a shared Buckets link
 * 
 * Used in: LinkCard component
 * Generated by: links-resolver service
 */
export interface CALSLinkData {
  // Content identification
  canonical_type: CALSLinkType
  canonical_id: string         // ID of the entity (track, event, etc.)
  url: string                  // Original URL
  short_url?: string           // bkt.to/xyz shortlink

  // Display metadata
  title: string
  description?: string
  image_url?: string
  thumbnail_url?: string

  // Content-specific data
  content_metadata?: {
    // For tracks
    artist_name?: string
    duration?: number
    genre?: string

    // For events
    event_date?: Date
    location?: string
    ticket_price_cents?: number

    // For artists
    follower_count?: number
    monthly_listeners?: number
  }

  // Attribution tracking
  utm_campaign?: string
  utm_source?: string
  utm_medium?: string
  source_app?: string          // Where link was shared from

  // DNA context (for personalization)
  dna_match_score?: number     // Match between sharer and recipient
}

/**
 * CALS Link Type
 * Types of content that can be shared via CALS
 * 
 * Maps to V2 Living Index entities
 */
export type CALSLinkType =
  | 'track'        // Music track (#6 Buckets Core)
  | 'album'        // Album/EP
  | 'artist'       // Artist profile
  | 'event'        // Event (#7 Concierto)
  | 'playlist'     // Playlist
  | 'offer'        // Brand offer (#10 Compañon)
  | 'brief'        // Sync brief (#9 Sync Library)
  | 'tournament'   // City-to-City match (#14)
  | 'locker'       // Locker content (#8)

// =============================================================================
// LINK TRACKING TYPES
// =============================================================================

/**
 * Link Open Event
 * Tracked event when a CALS link is opened
 * 
 * Used in: Attribution calculation, Analytics
 * Database: cals_link_events table
 * 
 * Privacy: No message content is read. Only link opens are tracked
 * when user explicitly clicks a Buckets link.
 */
export interface LinkOpenEvent {
  id: string
  link_id: string              // Reference to CALSThreadItem

  // Parties involved
  sender_user_id?: string      // User who shared (if known)
  receiver_user_id?: string    // User who opened (if authenticated)
  receiver_device_id?: string  // Device ID (if not authenticated)

  // Context
  source_app?: 'ios' | 'android' | 'web' | 'unknown'
  opened_from?: string         // "iMessage", "WhatsApp", "Instagram", etc.

  // Attribution tracking
  utm_campaign?: string
  utm_source?: string
  utm_medium?: string

  // Deep link data
  deep_link_params?: Record<string, string>

  // Session tracking
  session_id?: string
  is_first_open: boolean       // First time this person opened this link

  // Outcome tracking
  resulted_in_conversion: boolean
  conversion_type?: 'subscription' | 'ticket_purchase' | 'track_purchase'
  conversion_value_cents?: number

  // Metadata
  timestamp: Date
}

/**
 * Link Share Event
 * Tracked when user shares a link FROM Buckets
 * 
 * Used in: Coliseum funnel analysis
 * Database: cals_link_events table
 */
export interface LinkShareEvent {
  id: string

  // What was shared
  link_type: CALSLinkType
  entity_id: string

  // Who shared
  sharer_user_id: string

  // How it was shared
  share_method: 'native_sheet' | 'copy_link' | 'direct_message'
  target_app?: string          // "iMessage", "WhatsApp", etc. (if known)

  // Generated link
  short_url: string
  full_url: string

  // Attribution setup
  utm_campaign: string

  // DNA context (for later analysis of share effectiveness)
  sharer_dna_snapshot?: number[]  // Snapshot of sharer's DNA at share time

  // Metadata
  metadata?: Record<string, any>
  timestamp: Date
}

// =============================================================================
// CONSENT & PRIVACY TYPES
// =============================================================================

/**
 * CALS Consent Scope
 * User's consent preferences for CALS features
 * 
 * Used in: CALSSettings component
 * Database: cals_consent table
 * V2 Integration: #4 DIA (privacy oversight)
 * 
 * PRIVACY PRINCIPLE:
 * All CALS features are opt-in. No tracking without explicit consent.
 */
export interface CALSConsentScope {
  user_id: string

  // Core CALS features
  cals_basic: boolean          // Allow basic link tracking
  cals_threads: boolean        // Allow thread creation
  cals_attribution: boolean    // Allow attribution revenue

  // Optional features
  cals_brand: boolean          // Allow brand drops in threads (Locker integration)
  cals_analytics: boolean      // Allow anonymized analytics
  cals_recommendations: boolean // Allow DNA-based share recommendations

  // Data sharing
  allow_dna_matching: boolean  // Use DNA for personalization
  allow_device_tracking: boolean

  // Metadata
  granted_at: Date
  updated_at: Date
  revoked_at?: Date
}

// =============================================================================
// SHARE RECOMMENDATIONS (DNA-POWERED)
// =============================================================================

/**
 * Share Recommendation
 * DNA-based recommendation for who to share content with
 * 
 * Used in: ShareSheet component
 * Generated by: DNA matching algorithm + social graph
 * V2 Integration: #1 MediaID DNA → #5 CALS
 */
export interface ShareRecommendation {
  // Recommended recipient
  user_id: string
  user_name: string
  user_avatar_url?: string

  // Recommendation reasoning
  recommendation_score: number  // 0-1
  recommendation_reason: string // "Strong music taste match"

  // DNA matching
  dna_match_score: number
  matching_domains: string[]    // ["cultural", "spatial"]

  // Historical context
  previous_shares_count: number
  previous_opens_count: number
  previous_conversions_count: number

  // Estimated outcomes
  estimated_open_probability: number
  estimated_conversion_probability: number
  estimated_revenue_cents?: number
}

// =============================================================================
// DEEP LINKING TYPES
// =============================================================================

/**
 * Deep Link Config
 * Configuration for deep link handling
 * 
 * Used in: DeepLinkHandler component
 * Platform: iOS (Universal Links), Android (App Links), Web (fallback)
 */
export interface DeepLinkConfig {
  // URL patterns
  domain: string               // "buckets.media" or "bkt.to"
  path_pattern: string         // "/track/:id", "/event/:id"

  // Handling
  handler: 'native' | 'web' | 'fallback'
  fallback_url?: string        // Web URL if app not installed

  // Parameters
  required_params: string[]
  optional_params: string[]

  // Analytics
  track_opens: boolean
  create_thread: boolean       // Auto-create CALS thread
}

/**
 * Deep Link Payload
 * Parsed deep link data
 * 
 * Used in: DeepLinkHandler component
 */
export interface DeepLinkPayload {
  // Link identification
  link_type: CALSLinkType
  entity_id: string

  // Attribution
  sender_id?: string
  campaign_id?: string
  utm_params: Record<string, string>

  // Navigation target
  route: string
  params: Record<string, string>

  // Metadata
  timestamp: Date
}

// =============================================================================
// SHORTLINK TYPES
// =============================================================================

/**
 * Shortlink
 * bkt.to/xyz shortlink mapping
 * 
 * Used in: Link resolver service
 * Database: cals_shortlinks table
 */
export interface Shortlink {
  id: string
  short_code: string           // "xyz" in "bkt.to/xyz"

  // Target
  long_url: string
  link_type: CALSLinkType
  entity_id: string

  // Creator
  created_by: string

  // Analytics
  open_count: number
  unique_opens: number

  // Attribution
  campaign_id?: string

  // Lifecycle
  expires_at?: Date
  is_active: boolean

  // Metadata
  created_at: Date
}

// =============================================================================
// LOCKER INTEGRATION TYPES (BRAND DROPS)
// =============================================================================

/**
 * Thread Locker Drop
 * Brand offer/content dropped into a CALS thread
 * 
 * V2 Integration: #5 CALS + #8 Locker + #10 Compañon
 * Used in: ThreadView component (opt-in feature)
 * 
 * Privacy: Only shown if all thread members have cals_brand consent
 */
export interface ThreadLockerDrop {
  id: string
  thread_id: string

  // Drop content
  drop_type: 'offer' | 'content' | 'reward' | 'ticket'
  drop_data: {
    title: string
    description: string
    image_url: string
    value_cents?: number
    expires_at?: Date
  }

  // Brand/source
  brand_id?: string
  brand_name?: string

  // Targeting (DNA-based)
  target_dna_profile?: number[]
  min_dna_match?: number

  // Engagement
  view_count: number
  claim_count: number

  // Status
  is_active: boolean
  is_claimed: boolean

  // Metadata
  created_at: Date
}

// =============================================================================
// ANALYTICS TYPES (CALS-SPECIFIC)
// =============================================================================

/**
 * CALS Analytics Summary
 * Aggregated CALS metrics for a user
 * 
 * Used in: AttributionWidget, CALS dashboard
 */
export interface CALSAnalyticsSummary {
  user_id: string
  time_range: '7d' | '30d' | '90d' | 'all'

  // Sharing activity
  links_shared: number
  unique_recipients: number

  // Engagement
  links_opened: number
  open_rate: number            // Opens / Shares
  unique_openers: number

  // Conversion
  conversions: number
  conversion_rate: number      // Conversions / Opens
  conversion_types: Record<string, number>

  // Revenue
  total_attributed_revenue_cents: number
  pending_revenue_cents: number
  settled_revenue_cents: number

  // Top performers
  top_shared_content: Array<{
    link_type: CALSLinkType
    entity_id: string
    entity_name: string
    share_count: number
    open_rate: number
    revenue_cents: number
  }>

  generated_at: Date
}

// =============================================================================
// EXPORTS
// =============================================================================

// All types exported for use across the application
// Import as: import { CALSThread, LinkOpenEvent } from '@/types/cals'

