/**
 * =============================================================================
 * MEDIAID DNA TYPE DEFINITIONS
 * =============================================================================
 * 
 * Part of: Buckets V2 Trinity Architecture
 * V2 Living Index: #1 MediaID (Citizen ID + DNA)
 * Frontend Architecture: Trinity → MediaID System
 * 
 * PURPOSE:
 * Core type definitions for the MediaID DNA system - the biological identity
 * layer that powers all personalization, matching, and resonance across the
 * Buckets Nation ecosystem.
 * 
 * CONCEPT:
 * MediaID DNA is a multi-dimensional vector representation of a user's
 * cultural identity, modeled after biological DNA:
 * - Cultural DNA: Music taste, artistic preferences, genre affinities
 * - Behavioral DNA: Engagement patterns, interaction habits, temporal rhythms
 * - Economic DNA: Spending patterns, value alignment, price sensitivity
 * - Spatial DNA: Geographic preferences, location-based resonance
 * 
 * DNA EVOLUTION:
 * DNA evolves through three mechanisms:
 * 1. Mirroring: DNA shifts toward engaged content (reinforcement learning)
 * 2. Decay: Old signals fade over time (carbon dating model)
 * 3. Amplification: Resonance with matching entities strengthens signals
 * 
 * INTEGRATION POINTS:
 * - Used by: DNAProfile, DNASimulator, DNAMatchScore components
 * - Consumed by: Coliseum Analytics (for audience insights)
 * - Enriched by: Player tracking, Concierto voting, CALS sharing
 * - Powers: Treasury attribution, Brand targeting, Event recommendations
 * 
 * DATABASE TABLES:
 * - mediaid_dna (main DNA storage with pgvector)
 * - mediaid_dna_evolution (evolution event log)
 * - mediaid_dna_clusters (for audience segmentation)
 * 
 * =============================================================================
 */

// =============================================================================
// CORE DNA TYPES
// =============================================================================

/**
 * DNA Domain Types
 * The four dimensions of MediaID DNA, each representing a different
 * aspect of user identity and behavior
 */
export type DNADomain = 'cultural' | 'behavioral' | 'economic' | 'spatial'

/**
 * DNA Vector
 * A single domain's DNA representation as a 768-dimensional embedding
 * with confidence scoring and temporal tracking
 * 
 * Used in: All DNA operations
 * Database: Stored using pgvector extension
 */
export interface DNAVector {
  vector: number[]           // 768-dimensional embedding (OpenAI ada-002 compatible)
  confidence: number         // 0-1 confidence score based on data richness
  last_updated: Date         // For decay calculations
}

/**
 * MediaID DNA
 * Complete DNA profile for a user containing all four domain vectors
 * plus composite representation and metadata
 * 
 * Used in: DNAProfile, DNASimulator, Matching algorithms
 * Generated by: lib/dna/generator.ts
 * Evolved by: lib/dna/decay.ts (mirroring + decay)
 */
export interface MediaIDDNA {
  user_id: string
  
  // Multi-domain DNA (The "Double Helix")
  cultural_dna: DNAVector      // Music taste, cultural preferences, artist affinities
  behavioral_dna: DNAVector    // Engagement patterns, session frequency, interaction habits
  economic_dna: DNAVector      // Spending patterns, value alignment, price sensitivity
  spatial_dna: DNAVector       // Location preferences, geographic resonance, travel patterns
  
  // Composite representation (weighted combination of domains)
  composite_vector: number[]   // Combined vector for quick matching
  confidence_score: number     // Overall confidence (weighted avg of domain confidences)
  generation: number           // DNA version/evolution count (increments on major changes)
  
  // Metadata
  created_at: Date
  last_updated: Date
}

// =============================================================================
// DNA MATCHING TYPES
// =============================================================================

/**
 * DNA Match Result
 * Result of comparing two DNA profiles with domain-specific scores
 * and human-readable interpretation
 * 
 * Used in: DNAMatchScore component, Recommendation engine
 * Generated by: lib/dna/matcher.ts
 */
export interface DNAMatchResult {
  // Similarity scores (0-1, cosine similarity)
  composite_score: number      // Overall weighted match
  cultural_match: number       // Cultural domain similarity
  behavioral_match: number     // Behavioral domain similarity
  economic_match: number       // Economic domain similarity
  spatial_match: number        // Spatial domain similarity
  
  // Human-readable output
  interpretation: string       // "Strong match", "Moderate match", etc.
  reasons: string[]            // Why they match (domain-specific explanations)
  
  // Context for adaptive weighting
  context: DNAMatchContext
}

/**
 * DNA Match Context
 * Context determines domain weighting in matching algorithm
 * 
 * Examples:
 * - 'recommendation': Emphasizes cultural (music taste)
 * - 'targeting': Emphasizes economic (spending alignment)
 * - 'event': Balances cultural + spatial (music + location)
 * 
 * Used in: lib/dna/matcher.ts for context-adaptive weighting
 */
export type DNAMatchContext = 'recommendation' | 'targeting' | 'collab' | 'event'

// =============================================================================
// DNA EVOLUTION TYPES
// =============================================================================

/**
 * DNA Evolution Event
 * Log entry for DNA changes (mirroring, decay, or amplification)
 * 
 * Used in: DNAEvolutionTimeline component, Analytics
 * Logged by: All DNA modification operations
 * Database: mediaid_dna_evolution table
 */
export interface DNAEvolutionEvent {
  id: string
  user_id: string
  event_type: 'mirroring' | 'decay' | 'reinforcement'
  domain: DNADomain
  delta_vector: number[]       // Vector change applied
  trigger: string              // What caused the change (e.g., "voted_for_artist_abc")
  metadata?: Record<string, any>
  timestamp: Date
}

// =============================================================================
// DNA SIMULATOR TYPES (BREAKTHROUGH FEATURE)
// =============================================================================

/**
 * Simulated Action
 * A hypothetical user action for DNA simulation
 * 
 * Used in: DNASimulator component (credit score modeling for culture)
 * Purpose: Allow users to preview DNA changes before taking actions
 * 
 * Integration: Trinity → MediaID → DNA Simulator
 */
export interface SimulatedAction {
  type: 'attend_event' | 'subscribe' | 'share_track' | 'purchase' | 'vote'
  entity_id: string
  entity_type: 'event' | 'artist' | 'track' | 'brand' | 'offer'
  entity_dna: MediaIDDNA       // DNA of the entity being engaged with
}

/**
 * DNA Simulation Result
 * Complete outcome of simulating DNA changes from a set of actions
 * 
 * Used in: DNASimulator component
 * Generated by: lib/dna/simulator.ts
 * 
 * This is the "credit score modeling for culture" feature that makes
 * DNA tangible and actionable for users.
 */
export interface DNASimulation {
  actions: SimulatedAction[]
  
  outcomes: {
    // DNA shifts (before/after comparison)
    dna_shift: Record<DNADomain, {
      before: DNAVector
      after: DNAVector
      delta_percent: number      // Percentage change
    }>
    
    // New opportunities unlocked
    new_recommendations: Array<{
      entity_type: string
      entity_id: string
      match_score: number        // Match score with projected DNA
      reason: string             // Why this is recommended
    }>
    
    // Brand offers qualified for
    brand_offers_unlocked: BrandOffer[]
    
    // Revenue projections
    estimated_earnings: {
      referrals: number          // CALS referral earnings (cents)
      attributions: number       // Attribution earnings (cents)
      total: number              // Total projected earnings (cents)
    }
    
    // Network effects
    resonance_amplification: number  // New connections unlocked
  }
}

/**
 * Brand Offer
 * A brand offer that may be unlocked by DNA matching
 * 
 * Integration: MediaID DNA → Compañon (Brand Layer) → Locker
 * V2 Living Index: #10 Compañon (Brand Activation Layer)
 */
export interface BrandOffer {
  id: string
  brand_id: string
  brand_name: string
  description: string
  value_cents: number
  dna_requirements?: {
    min_match_score: number
    required_domains?: DNADomain[]
  }
  expires_at: Date
  created_at: Date
}

// =============================================================================
// DNA CLUSTERS & INSIGHTS (FOR COLISEUM ANALYTICS)
// =============================================================================

/**
 * DNA Cluster
 * Groups of users with similar DNA profiles
 * 
 * Used in: Coliseum Analytics → DNA Compatibility Report
 * Generated by: Clustering algorithm (k-means on composite vectors)
 * V2 Living Index: #3 Coliseum Analytics
 */
export interface DNACluster {
  id: string
  centroid: number[]           // Center of cluster in DNA space
  size: number                 // Number of users in cluster
  label: string                // Human-readable label (e.g., "Electronic Enthusiasts")
  dominant_domains: DNADomain[]
  metadata?: {
    avg_age?: number
    top_genres?: string[]
    geographic_concentration?: string
  }
  created_at: Date
}

/**
 * DNA Insights
 * Aggregated DNA analytics for an entity (artist, event, brand)
 * 
 * Used in: Coliseum Analytics dashboards, DIA oversight
 * Integration: MediaID DNA → Coliseum Analytics → Treasury (for targeting value)
 */
export interface DNAInsights {
  entity_id: string
  entity_type: 'artist' | 'event' | 'brand'
  
  // Match statistics
  average_match_score: number
  match_distribution: {
    strong: number             // % with >0.8 match
    good: number               // % with 0.6-0.8 match
    moderate: number           // % with 0.4-0.6 match
    weak: number               // % with <0.4 match
  }
  
  // Domain breakdown
  top_matching_domains: Array<{
    domain: DNADomain
    avg_score: number
  }>
  
  // Audience segmentation
  audience_clusters: DNACluster[]
  
  // Temporal trends
  match_score_trend: 'improving' | 'stable' | 'declining'
  
  generated_at: Date
}

// =============================================================================
// DNA CONSENT & PRIVACY
// =============================================================================

/**
 * DNA Consent Scope
 * User consent for DNA data usage
 * 
 * Used in: ConsentManager component, MediaID Settings
 * Integration: MediaID DNA → DIA (privacy oversight)
 * V2 Living Index: #4 DIA (Department of Internal Affairs)
 */
export interface DNAConsentScope {
  user_id: string
  
  // Consent levels
  dna_generation: boolean      // Allow DNA generation from behavior
  dna_evolution: boolean       // Allow DNA to evolve via mirroring/decay
  dna_matching: boolean        // Allow DNA matching for recommendations
  dna_analytics: boolean       // Allow anonymized DNA in analytics
  dna_brand_targeting: boolean // Allow brand targeting via DNA
  
  // Metadata
  granted_at: Date
  updated_at: Date
}

// =============================================================================
// HELPER TYPES
// =============================================================================

/**
 * DNA Generation Config
 * Configuration for DNA generation pipeline
 * 
 * Used in: lib/dna/generator.ts
 */
export interface DNAGenerationConfig {
  domains: DNADomain[]         // Which domains to generate
  data_sources: {
    cultural?: {
      include_listening_history: boolean
      include_voting_history: boolean
      include_subscriptions: boolean
    }
    behavioral?: {
      session_lookback_days: number
      min_interactions: number
    }
    economic?: {
      transaction_lookback_days: number
      include_browsing_data: boolean
    }
    spatial?: {
      include_event_locations: boolean
      include_ip_geolocation: boolean
    }
  }
}

/**
 * DNA Decay Config
 * Configuration for temporal decay model
 * 
 * Used in: lib/dna/decay.ts
 */
export interface DNADecayConfig {
  half_life_days: number       // Days until signal decays to 50%
  min_retention: number        // Minimum retention ratio (0-1)
  domain_specific?: {
    cultural?: number          // Domain-specific half-life overrides
    behavioral?: number
    economic?: number
    spatial?: number
  }
}

// =============================================================================
// EXPORTS
// =============================================================================

// All types exported for use across the application
// Import as: import { MediaIDDNA, DNAMatchResult } from '@/types/dna'

